### ISSUE TITLE
Query and Mutation level authorization

### ISSUE THREAD

**Issue by stochris** [Folkloreatelier/laravel-graphql#119]
I'm proposing implementing an (optional) authorization function for each query / mutation, something similar to how Laravel Form Requests works, with the difference that, by default, the authorization method returns true.
An advantage would be that diffent concerns reside in different methods inside a query / mutation, and the fact that you could have different types of queries.
I looked into overriding the default `GraphQLController`, but at that point, you cannot know the queries or mutations that will be accessed.

What do you think?

**Comment by rebing** [comment]
@stochris I have actually implemented this feature in my version of this package: https://github.com/rebing/graphql-laravel/blob/master/docs/advanced.md#authorization

**Comment by dmongeau** [comment]
I would be glad to merge this in this repo if you are willing to do a PR!

**Comment by stochris** [comment]
Great.

What should happen when the authorization fails?
I see 2 options:
- return the relevant http code ( 401 )
- return a 200 http code with a certain response body

What do you think?

**Comment by stochris** [comment]
@rebing thank you very much.

I currently have a app in production that already this package tho

**Comment by SonarSoftware** [comment]
@stochris That is a good question, and I can see valid arguments either way. Especially since it is possible you're not authorized to view a certain relation, but you may be authorized to view the parent object, it would be a lot more clear to a consumer of the API if they receive the parent data, and get a typical GraphQL error in regards to the relation, rather than just returning a 401.

**Comment by barbu110** [comment]
Anything on this yet?

**Comment by dmongeau** [comment]
It has been added, you can add an `authorize` method in you queries and mutations.
