### ISSUE TITLE
Different middleware for different queries/mutations?

### ISSUE THREAD

**Issue by tremby** [Folkloreatelier/laravel-graphql#156]
How can I assign middlewares per query or mutation?

I have some queries and mutations which are public, others which require auth, and others which require auth and a particular user privilege.

**Comment by andrewdalpino** [comment]
+1 for this feature

**Comment by niiapa** [comment]
There's no clear documentation of this. I like the library so far but I'm stuck on this, have been for a while. The documents assume you know everything to do besides writing Queries and Mutations. I'm not sure how to tackle this problem either so if anyone could please assist, it would be appreciated. Thanks.

**Comment by n1ru4l** [comment]
Couldn't you parse the mutation or query name inside a middleware and apply
it if it contains the name?

**Comment by tremby** [comment]
That sounds horrible.

Right now I'm doing something equally horrible, and overriding `getResolver` in the mutation:

```php
    protected function getResolver()
    {
        // TODO: do this via middleware, remove this entire method
        $resolver = parent::getResolver();
        if (!$resolver) {
            return null;
        }

        return function () use ($resolver) {
            $arguments = func_get_args();

            // Ensure user has permission
            $user = app('auth')->user();
            if (!$user || !$user->enabled || !$user->has_whatever_special_permission) {
                throw new UnauthorizedHttpException('auth', 'unauthorized');
            }

            return call_user_func_array($resolver, $arguments);
        };
    }
```

What we need is a way to tell each mutation/query which middlewares to apply, [just like we tell a controller which middlewares to apply in Laravel](https://laravel.com/docs/5.4/controllers#controller-middleware).

**Comment by SonarSoftware** [comment]
Do you guys think middleware is the right approach to this? I didn't use that approach, since I generally don't implement middleware that would need to be different for each call, I mostly use it for things that would be consistent across the application.

My approach to this was to have each of my queries and mutations extend from a base query/mutation, impose the permission checking logic in the base query/mutation, and provide the needed data in the extending query or mutation to be used in the check. If the needed data wasn't provided (e.g. user ID must be equal to 1, or whatever) then the base query/mutation defaults to deny.

**Comment by tremby** [comment]
Middleware is the Laravel way to do it, I think.

If every query requires different logic then sure, things will get out of hand: it'd be a mess to have a whole pile of middlewares which are each only used once.

Both approaches should certainly be possible.

Can you show us how your approach works? I'm keen to improve my own.

**Comment by SonarSoftware** [comment]
Yeah, middleware is the Laravel way to do it, but I think it only makes sense if you can impose all the logic within the middleware itself, rather than applying unique middleware to each query/groups of queries.

My method is fairly complex, because my query resolution logic is pretty complex, but the gist of it is that each query and type inherits from a base query or type. The base query is responsible for resolving the root query. The base type recursively iterates the relationships that I have defined, and uses a deferred resolver (http://webonyx.github.io/graphql-php/data-fetching/#solving-n1-problem) to fetch and return the data.

So, in my application, there are really only two places the 'magic happens' - in the deferred resolution, or in the root query. In my base query, I have a check that looks to see if the root type is allowed to be fetched (by just checking against a permission service I built - does this user have read permission for 'Accounts' or 'Credit Cards' or whatever.) In the deferred resolution, I have built logic to check if the user has permission for the related type, or, in the case of polymorphic relations, it looks back up at the root to see if the user has permission.

The tricky part is when loading polymorphic objects as the root object. In that case, I have another path which will look at the polymorphic relationship to determine which other types the user has access to view, and will then limit the results accordingly.

With this approach, since all the logic lives in the base classes, and the default behavior is to deny, if someone doesn't map up the proper authorization structure, the queries will just fail with an unauthorized error.
Migrations (IMO) are much easier, as you typically are just checking if a user has a particular authorization. At least, that is how I structure my migrations to keep it clean. So in my base mutation class, I just have a mapping of which mutations require which permission, and it's a pretty simple boolean check.

**Comment by tremby** [comment]
I think we're in agreement that both approaches ought to be possible, so the developer can choose which is most appropriate in any given situation.

I understand roughly how your approach works, but I'd really like to see some code. Forget the inheritance and the deferred logic for a moment and imagine the auth check is a one-liner: where in your query/mutation class do you have it and what exactly do you do when you want to deny?

My code is a mess in my eyes, and I'd like to find out if there's a better way.

**Comment by SonarSoftware** [comment]
It's a bit tough to put in without looking at the rest, but basically:

In my query class, I have it at the beginning of the 'resolve' function.
This doesn't work for relations, because I resolve relationships using the deferred method I mentioned above, and this is actually set on the 'type' class, but it's basically the same logic there.

If you start with the query, it's pretty simple. I have a service that maps up types to permissions. So let's say I have permission ID 1, which is 'accounts' and it is a CRUD permission. In my query, I ask the permission service 'which is the permission associated with 'accounts' objects? The service replies, 1. Then I ask a service that maps permissions to users, 'OK, does Auth::user() have "READ" on permission ID 1?' That service says true or false. If it is false, I throw a special exception. This exception is handled in my custom GraphQL error formatter, and it bubbles up a standard GraphQL error that says 'You don't have permission to view "accounts". You need permission ID 1'.

It's essentially the same logic for relationships (and might just work like that for you, if you're not resolving deferred relations inside the type like I am.)

**Comment by SonarSoftware** [comment]
As an aside, I did try doing this as a middleware, but I just didn't feel like it worked well. There are some cases where I have to override this standardized permission behavior (as our application is very complex) and it's much easier to override it when you're extending from a base class, by just overriding the function, than it is to go try and hack stuff into a global middleware.

**Comment by tremby** [comment]
> In my query class, I have it at the beginning of the 'resolve' function.

And it sounds like you do the same in your mutation class.

OK, the problem I had with this, and the reason I resorted to overriding `getResolver`, is that inputs are validated (with `rules`) before `resolve` runs. This means an unauthenticated user will get errors about the specific inputs they gave, rather than an error saying they're not authenticated. This wasn't acceptable to me.

**Comment by SonarSoftware** [comment]
So the actual implementation of authentication, I do in middleware, so if someone is not authenticated, they never even make it to the resolver.

**Comment by tremby** [comment]
But then you can't have a graphql query which does *not* require authentication, can you?

**Comment by tremby** [comment]
...and how do you know in the middleware what specific permission the user needs, if that isn't determined until the resolve method runs, as you explained above?

**Comment by SonarSoftware** [comment]
> ...and how do you know in the middleware what specific permission the user needs, if that isn't determined until the resolve method runs, as you explained above?

I don't, but I already know they are authenticated at that point, they're just not authorized. I don't really mind them knowing the validation rules (I mean, they can see all the params in the GraphQL introspection anyway.)

> But then you can't have a graphql query which does not require authentication, can you?

I don't have any that don't require auth, but if I was going to, I would probably try putting my unauthenticated queries in a different schema, and then using the 'routes' section of graphql.php to send different schemas to different endpoints. I can then check the endpoint in the middleware before deciding what to do.

**Comment by tremby** [comment]
Good points.

I had also overlooked the fact that multiple queries can be combined in a single request. I think that alone makes this whole issue moot: what if queries with different auth requirements are made in the same request? I don't think middleware can handle that situation.
