### ISSUE TITLE
ID field doesn't work with UUIDs

### ISSUE THREAD

**Issue by jradtilbrook** [Folkloreatelier/laravel-graphql#213]
I've been trying to get this to work as per the examples but can't seem to find the issue. I have a single table backed by a UUID primary key with other generic fields (those work fine). When I query for the id of the type/model/etc it returns a value as if it as been typecast to an int.

Eg. A row has a PK of `55c5e739-0a5b-410c-9b89-9af83c9e085d`, but the id field in the response is `55`. This is consistent across all returned objects. If the UUID begins with a character the ID returned is 0.

The corresponding type is set to a string and the resolve method of the query returns the Eloquent ::all() results so no mapping is done on my end.

Is anyone able to help me out with this issue?

**Comment by jakobploens** [comment]
Same issue here, but with character-only IDs (for a list of countries, I'm using ISO 3166-1 alpha 2 codes). ID is always returned as 0, but both Query and Type are setting the ID as string.

**Comment by devlobchannel** [comment]
I am using a PHP based library for UUID.

This one

The solution to your problem is to convert the UUID to a string, like this.

**<?php

namespace App\Utopia;
use Ramsey\Uuid\Uuid;

trait Uuids
{
    protected static function boot()
    {
        parent::boot();
        static::creating(function ($model) {
            $model->{$model->getKeyName()} = (string)Uuid::uuid4();
        });
    }
}**

This is a trait that I use in every model. Inside the model, just do this:

**use Uuids;
public $incrementing = false;**

Regarding my fields, I use the ID type

**'id' => [
    'type' => Type::nonNull(Type::id()),
],**
