### ISSUE TITLE
Query Variables Empty

### ISSUE THREAD

**Issue by diegomengarda** [Folkloreatelier/laravel-graphql#388]
Hey guys i'm trying to use query variables in my app but the value of the variables is empty.

Here is my code.

```php
class UsersQuery extends Query
{

    protected $attributes = [
        'name' => 'Users Query',
        'description' => 'A query of users',
        'model' => User::class
    ];

    public function type()
    {
        return GraphQL::paginate('users');
    }

    public function args()
    {
        return [
            'id' => [
                'name' => 'id',
                'type' => Type::int()
            ],
            'limit' => [
                'name' => 'limit',
                'type' => Type::int()
            ],
            'page' => [
                'name' => 'page',
                'type' => Type::int()
            ],
            'filters' => [
                'name' => 'filters',
                'type' => Type::listOf(GraphQL::type('filter'))
            ]
        ];
    }

    public function resolve($root, $args)
    {
        dd('$args', $args);
    }
}
```

```php
class FilterType extends GraphQLType
{

    protected $inputObject = true;

    protected $attributes = [
        'name' => 'FilterType',
        'description' => 'A type'
    ];

    public function fields()
    {
        return [
            'field' => [
                'name' => 'field',
                'type' => Type::nonNull(Type::string())
            ],
            'rule' => [
                'name' => 'rule',
                'type' => Type::string()
            ],
            'value1' => [
                'name' => 'value1',
                'type' => Type::nonNull(Type::string())
            ],
            'value2' => [
                'name' => 'value2',
                'type' => Type::string()
            ]
        ];
    }
}
```

Query and result
![image](https://user-images.githubusercontent.com/8545323/46020843-ab477280-c0b5-11e8-89c1-fc572464dc03.png)

**I already tried remove the "params" from the query variables but the result was empty too.**

Anyone can help me with this problem ?

Thanks!

**Comment by mfn** [comment]
I'm not sure but a few things pop up to me which look weird…

This is the name of the query for the outside, yet in your example you use `fetchUsers`?
![image](https://user-images.githubusercontent.com/87493/46022646-47d43980-c0e3-11e8-9e41-d4542f30f0a1.png)

Is this filter supposed to be the same? Because the names/cases are different. IMHO both should just be `Filter`:
![image](https://user-images.githubusercontent.com/87493/46022695-63d7db00-c0e3-11e8-9be5-fcc473801f2d.png)

Not sure about the last, but in your Screenshot `params` is red underlined and you don't use `$params` in your query.

I could be wrong but on the first glance, things simply look a bit off here.

**Comment by diegomengarda** [comment]
This config allows me to use the short names
My types and queries are registrated like that:
```php
'types' => [
    'filter' => FilterType::class
]
'query' => [
    'users' => UsersQuery::class
]
```
And like a said i already tested the query without the "params".

**Comment by diegomengarda** [comment]
I had to remove the attribute model from UsersQuery to work correctly
