### ISSUE TITLE
Help needed - resolve call to microservice(s)

### ISSUE THREAD

**Issue by renepardon** [Folkloreatelier/laravel-graphql#392]
Hello,

can't find a hint/solution on how to call an additional service form within the resolve method within a query.
For example I've setup folklore/laravel-graphql as API Gateway. This gateway should communicate with microservices for example. A few of the internal API's will also implement GraphQL pattern but it highly depends on the service and may differ.

Long story short, I try the following:

```php
public function resolve($root, $args)
{
    $result = (new \App\Http\Clients\User())->sendRequest(request()->get('query'));
    // TODO map this response to an object/iterable before we are able to return it

    return $result;
}
```

Whereas User is a guzzle client configured the following way:

```php
class User
{
    /**
     * @var Client
     */
    private $client;

    /**
     * UserHttpClient constructor.
     */
    public function __construct()
    {
        $this->client = new Client(['base_uri' => 'http://user:9000/graphql']); // base_uri will be read from environment configuration :)
    }

    public function sendRequest(string $query)
    {
        try {
            $res = $this->client->post(null, ['form_params' => ['query' => $query]]);
        } catch (BadResponseException $exception) {
            throw new HttpException(
                $exception->getCode(),
                json_decode($exception->getResponse()->getBody()->getContents())
            );
        }

        return json_decode($res->getBody()->getContents());
    }
}
```

So far so good but how would you decorate the response to return an iterable within the resolve method to match the **GraphQL/Type/UserType.php** type? Also it's not that nice to just pass the request query through **request()->get('query')**. Maybe we can access the request from within GraphQL instances somehow in the future?

**Comment by mfn** [comment]
> So far so good but how would you decorate the response to return an iterable within the resolve method to match the **GraphQL/Type/UserType.php** type?

The default resolver (which is actually provided by the underlying webonyx library) can out of the resolve arrays whose key match or objects whose properties match (that's why Laravels models usually "work out of the box ™️").

If you get black plain arrays, you're responsible to convert it. Is the result you can back from the service _per se_ compatible with your UserType? Then just return the array (of user arrays, etc.). Or you have to apply manual transformation yourself.

Is that what you were asking for?

> Also it's not that nice to just pass the request query through **request()->get('query')**. Maybe we can access the request from within GraphQL instances somehow in the future?

In your resolver you shouldn't access the GET parameters; that's an anti pattern (unless you know exactly what you're doing).

That's why you have your `$args` pass to your resolve. You also have access to the `$context` (by default the currently authenticated user).

If you need more, there's a forth parameter `ResolveInfo $info` with which you can _peek_ into the requested fields via `getFieldSelection()`. Should be avoided but sometimes it's just necessary (my experience).

**Comment by renepardon** [comment]
Didn't saw the $info attribute. Thanks for this information! :)

Finally got it working with this piece of code within the UsersQuery class from the API gateway:

```php
    /**
     * @param             $root
     * @param array       $args
     * @param             $context
     * @param ResolveInfo $info
     *
     * @return User[]|\Illuminate\Database\Eloquent\Collection
     */
    public function resolve($root, array $args, $context, ResolveInfo $info)
    {
        $query = new GraphQLClientQuery('users', $args, array_keys($info->getFieldSelection()));
        /** @var UserClient $client */
        $client = app()->make(UserClient::class);
        $result = $client->query($query);

        return $result->getData();
    }
```
Where **GraphQLClientQuery** is from the package https://packagist.org/packages/renepardon/graphql-client-php and **UserClient** is a client which gets constructed with Guzzle through IoC and which extends the graphql-client-php Client class to perform the required request.

thx @mfn
