### ISSUE TITLE
Shared "context" between mutations?

### ISSUE THREAD

**Issue by belohlavek** [Folkloreatelier/laravel-graphql#53]
Is there any way to share $root between mutations? Something like:
https://github.com/webonyx/graphql-php/blob/master/tests/Executor/MutationsTest.php#L68-L85

Since mutations are executed serially in the order given, I'm trying to achieve something like the following ([source article](https://medium.com/apollo-stack/a-guide-to-authentication-in-graphql-e002a4039d1#.se0jx3ard)):

```
mutation something {
  loginWithToken(token: "6e37a03e-9ee4-42fd-912d-3f67d2d0d852"),
  do_stuff(greeting: "Hello", name: "Tom"),
  do_more_stuff(submarine_color: "Yellow")
}
```

Where the user is authenticated in the first mutation, and stays "available" for all subsequent ones.

I tried this idea and $root seems to be `null` inside my mutation's `resolve()` method!

Any tips are appreciated, thanks for reading 😁

**Comment by dmongeau** [comment]
I think it doesn't work that way. If you look at the example you are sending, the second (and other) mutation doesn't receive the $root from the previous mutation. They all receive the same $root which was passed at the execute method. The test is only checking if it executes in the right order according to the GraphQL specification described here: https://facebook.github.io/graphql/#sec-Serial-execution

To do what you intent, first the login should, in my opinion, be done via a header with the token and handled with the auth middleware, or be part of the arguments of your mutations. For the mutations, since GraphQL execute them one after the other it kind of does what you want except you will have to manually retrieve the results of the mutation before (from your database for example).

**Comment by belohlavek** [comment]
@dmongeau thanks for the quick reply!

Then.. what's $root used for in mutations?

**Comment by dmongeau** [comment]
It's not specific to mutations, the $root is always null at the top level if don't give a "starting root" to the GraphQL execute method.

**Comment by belohlavek** [comment]
@dmongeau this would be the execute method right? 
https://github.com/Folkloreatelier/laravel-graphql/blob/5d6be2ababfe0974d85e0e53bd6a5892e8e1e442/src/Folklore/GraphQL/GraphQL.php#L117

I know auth is done via the header with a token bearer. But if I were to change that inital null for something else.. I should be able to pull it off, right? 😈

**Comment by dmongeau** [comment]
Yeah but the GraphQL facade doesn't support to pass an initial $root as you can see in the example you send. So you will have recreate the method `queryAndReturnResult` yourself or just call this, from your controller (or anywhere else):

```
$schema = GraphQL::schema();
$result = GraphQLBase::executeAndReturnResult($schema, $query, null, $params);
```

**Comment by belohlavek** [comment]
I definitively got it to work. Nice experiment, thanks!
