### ISSUE TITLE
API Authentication

### ISSUE THREAD

**Issue by mxmtsk** [Folkloreatelier/laravel-graphql#73]
Hey,

I have a GraphQL Api and I wanna protect some queries with with this recently introduced API Authentication:

https://laravel.com/docs/5.3/passport 

But I only want to protect certain queries, not all of them, as there are a few public ones. Is this possible yet and if so, how?

**Comment by n1ru4l** [comment]
You would need to reimplement the GaphQLController Class.
In the `config/graphql.php` you can specify the controller:
`'controllers' => \Folklore\GraphQL\GraphQLController::class.'@query',`

Then in your request you can send the key as a header, extract it in that function and assign it to the context instead of the default way in the `queryContext` Method.

In your resolver methods the third argument will be equal to the context.

**Comment by 4levels** [comment]
Hi,

I can get authorization support with Laravel's Passport, in Lumen, using OAuth tokens as described in the Passport setup - please note I did need https://github.com/dusterio/lumen-passport to have it working in Lumen.

All I needed to do was updating `config/graphql.php` in my Lumen config folder..

    // Any middleware for the graphql route group
    'middleware' => [ 'auth:api', 'scope:graphql' ],

Hope this helps..
